export const postalCodeRegexes: Record<string, RegExp> = {
  'Aland Islands': /^[A-Z]{2}[ ]?\d{4}$/,
  Algeria: /^\d{5}$/,
  'American Samoa': /^(96799)$/,
  Andorra: /^(AD)?\d{3}$/,
  Argentina: /^([A-HJ-NP-Z])?\d{4}([A-Z]{3})?$/,
  Armenia: /^(37)?\d{4}$/,
  Australia: /^\d{4}$/,
  Austria: /^\d{4}$/,
  Azerbaijan: /^\d{4}$/,
  Bahrain: /^((1[0-2]|[2-9])\d{2})?$/,
  Bangladesh: /^\d{4}$/,
  Barbados: /^(BB)?\d{5}$/,
  Belarus: /^\d{6}$/,
  Belgium: /^\d{4}$/,
  Bermuda: /^[A-Z]{2}[ ]?[A-Z0-9]{2}$/,
  Brazil: /^\d{5}[-]?\d{3}$/,
  'British Indian Ocean Territory': /^(IO)?BBND 1ZZ$/,
  Brunei: /^[A-Z]{2}[ ]?\d{4}$/,
  Bulgaria: /^\d{4}$/,
  Cambodia: /^\d{5}$/,
  Canada: /^[ABCEGHJKLMNPRSTVXY]\d[ABCEGHJ-NPRSTV-Z][ ]?\d[ABCEGHJ-NPRSTV-Z]\d$/,
  'Cape Verde': /^\d{4}$/,
  Chile: /^\d{7}$/,
  China: /^\d{6}$/,
  'Christmas Island': /^(6798)$/,
  'Cocos Islands': /^(6799)$/,
  Colombia: /^\d{6}$/,
  'Costa Rica': /^\d{4,5}|\d{3}-\d{4}$/,
  Croatia: /^\d{5}$/,
  Cyprus: /^\d{4}$/,
  'Czech Republic': /^\d{3}[ ]?\d{2}$/,
  Denmark: /^\d{4}$/,
  'Dominican Republic': /^\d{5}$/,
  Ecuador: /^([A-Z]\d{4}[A-Z]|(?:[A-Z]{2})?\d{6})?$/,
  Egypt: /^\d{5}$/,
  Estonia: /^\d{5}$/,
  Ethiopia: /^\d{4}$/,
  'Faroe Islands': /^\d{3}$/,
  'Falkland Islands': /^(FIQQ 1ZZ)$/,
  Finland: /^\d{5}$/,
  France: /^\d{2}[ ]?\d{3}$/,
  'French Guiana': /^(9[78]3d{2})$/,
  'French Polynesia': /^(987d{2})$/,
  Georgia: /^\d{4}$/,
  Germany: /^\d{5}$/,
  Gibraltar: /^[A-Z]{2}[0-9]{1,2} [0-9][A-Z]{2}$/,
  Greece: /^\d{3}[ ]?\d{2}$/,
  Greenland: /^39d{2}$/,
  Guadeloupe: /^(9[78][01]\d{2})$/,
  Guam: /^(969[123]\d)([ -]\d{4})?$/,
  Guatemala: /^\d{5}$/,
  Guernsey: /^(GY)?[0-9]{1,2} [0-9][A-Z]{2}$/,
  Guinea: /^\d{3}$/,
  'Guinea-Bissau': /^\d{4}$/,
  Guyana: /^\d{3}$/,
  Haiti: /^\d{4}$/,
  'Heard Island and McDonald Islands': /^(7d{2})$/,
  Honduras: /^(?:\d{5})?$/,
  Hungary: /^\d{4}$/,
  Iceland: /^\d{3}$/,
  India: /^\d{6}$/,
  Indonesia: /^\d{5}$/,
  Iraq: /^\d{5}$/,
  Ireland: /^[A-Z]{3}[ ]?\d{4}$/,
  'Isle of Man': /^(IM)?[0-9]{1,2} [0-9][A-Z]{2}$/,
  Israel: /^\d{5}$/,
  Italy: /^\d{5}$/,
  Jamaica: /^\d{2}$/,
  Japan: /^\d{3}-\d{4}$/,
  Jersey: /^(JE)?[0-9]{1,2} [0-9][A-Z]{2}$/,
  Jordan: /^\d{5}$/,
  Kazakhstan: /^\d{6}$/,
  Kenya: /^\d{5}$/,
  Kuwait: /^\d{5}$/,
  Kyrgyzstan: /^\d{6}$/,
  Laos: /^\d{5}$/,
  Latvia: /^\d{4}$/,
  Lebanon: /^(\d{4}([ ]?\d{4})?)?$/,
  Lesotho: /^\d{3}$/,
  Liberia: /^\d{4}$/,
  Liechtenstein: /^(948[5-9])|(949[0-7])$/,
  Lithuania: /^\d{5}$/,
  Luxembourg: /^\d{4}$/,
  'North Macedonia': /^\d{4}$/,
  Madagascar: /^\d{3}$/,
  Malaysia: /^\d{5}$/,
  Maldives: /^\d{5}$/,
  Malta: /^[A-Z]{3}[ ]?\d{2,4}$/,
  'Marshall Islands': /^(969[67]\d)([ -]\d{4})?$/,
  Martinique: /^(9[78]2d{2})$/,
  Mauritius: /^(\d{3}[A-Z]{2}\d{3})?$/,
  Mexico: /^\d{5}$/,
  Micronesia: /^(9694[1-4])([ -]\d{4})?$/,
  Moldova: /^\d{4}$/,
  Monaco: /^\d{5}$/,
  Mongolia: /^\d{6}$/,
  Montenegro: /^(8d{4})$/,
  Morocco: /^\d{5}$/,
  Mozambique: /^\d{4}$/,
  Namibia: /^\d{5}$/,
  Nauru: /^\d{4}$/,
  Nepal: /^\d{5}$/,
  Netherlands: /^\d{4}[ ]?[A-Z]{2}$/,
  'New Caledonia': /^(988d{2})$/,
  'New Zealand': /^\d{4}$/,
  Nicaragua: /^\d{5}$/,
  Niger: /^\d{4}$/,
  Nigeria: /^\d{6}$/,
  Niue: /^\d{4}$/,
  'Norfolk Island': /^(2899)$/,
  'Northern Mariana Islands': /^(9695[012])([ -]\d{4})?$/,
  Norway: /^\d{4}$/,
  Oman: /^(PC )?\d{3}$/,
  Pakistan: /^\d{5}$/,
  Palau: /^(96940)$/,
  Palestine: /^\d{5}$/,
  Panama: /^\d{6}$/,
  'Papua New Guinea': /^\d{3}$/,
  Paraguay: /^\d{4}$/,
  Peru: /^\d{5}$/,
  Philippines: /^\d{4}$/,
  'Pitcairn Islands': /^(PCRN 1ZZ)$/,
  Poland: /^\d{2}-\d{3}$/,
  Portugal: /^\d{4}([-]\d{3})?$/,
  'Puerto Rico': /^(00[679]\d{2})([ -]\d{4})?$/,
  Qatar: /^(4[0-4]\d{2})$/,
  Romania: /^\d{6}$/,
  Russia: /^\d{6}$/,
  Rwanda: /^\d{4}$/,
  'Saint Barthelemy': /^(9[78][01]\d{2})$/,
  'Saint Helena': /^(ASCN|STHL) 1ZZ$/,
  'Saint Kitts and Nevis': /^(KN)?[0-9]{4}$/,
  'Saint Lucia': /^(LC)?[0-9]{5}$/,
  'Saint Martin': /^(9[78][01]\d{2})$/,
  'Saint Pierre and Miquelon': /^(9[78]5d{2})$/,
  'Saint Vincent and the Grenadines': /^(VC)?[0-9]{5}$/,
  Samoa: /^\d{5}$/,
  'San Marino': /^(4789d)$/,
  'Sao Tome and Principe': /^\d{4}$/,
  'Saudi Arabia': /^\d{5}$/,
  Senegal: /^\d{5}$/,
  Serbia: /^\d{6}$/,
  'Serbia and Montenegro': /^\d{5}$/,
  Seychelles: /^\d{3}$/,
  'Sierra Leone': /^\d{4}$/,
  Singapore: /^\d{6}$/,
  Slovakia: /^\d{3}[ ]?\d{2}$/,
  Slovenia: /^\d{4}$/,
  'Solomon Islands': /^\d{5}$/,
  Somalia: /^\d{5}$/,
  'South Africa': /^\d{4}$/,
  'South Georgia and the South Sandwich Islands': /^(SIQQ 1ZZ)$/,
  'South Korea': /^\d{3}[-]\d{3}$/,
  Spain: /^\d{5}$/,
  'Sri Lanka': /^\d{5}$/,
  Sudan: /^\d{5}$/,
  Suriname: /^\d{4}$/,
  'Svalbard and Jan Mayen': /^\d{4}$/,
  Swaziland: /^[HLMS]\d{3}$/,
  Sweden: /^\d{3}[ ]?\d{2}$/,
  Switzerland: /^\d{4}$/,
  Syria: /^\d{5}$/,
  Taiwan: /^\d{3}(\d{2})?$/,
  Tajikistan: /^\d{6}$/,
  Tanzania: /^\d{5}$/,
  Thailand: /^\d{5}$/,
  'Timor-Leste': /^\d{4}$/,
  Togo: /^\d{4}$/,
  Tokelau: /^\d{4}$/,
  Tonga: /^\d{3}$/,
  'Trinidad and Tobago': /^\d{6}$/,
  Tunisia: /^\d{4}$/,
  Turkey: /^\d{5}$/,
  Turkmenistan: /^\d{6}$/,
  'Turks and Caicos Islands': /^(TKCA 1ZZ)$/,
  Tuvalu: /^\d{4}$/,
  Uganda: /^\d{5}$/,
  Ukraine: /^\d{5}$/,
  'United Arab Emirates': /^\d{5}$/,
  'United Kingdom': /^[A-Z]{1,2}[0-9R][0-9A-Z]? [0-9][A-Z]{2}$/,
  'United States': /^\d{5}([ -]\d{4})?$/,
  Uruguay: /^\d{5}$/,
  Uzbekistan: /^\d{6}$/,
  Vanuatu: /^\d{4}$/,
  'Vatican City': /^(00120)$/,
  Venezuela: /^\d{4}$/,
  Vietnam: /^\d{6}$/,
  'Virgin Islands': /^(008(([0-4]\d)|(5[01])))([ -]\d{4})?$/,
  'Wallis and Futuna': /^(986d{2})$/,
  'Western Sahara': /^\d{5}$/,
  Yemen: /^\d{5}$/,
  Zambia: /^\d{5}$/,
};

export const countryCodes = {
  'Aland Islands': 'AX',
  Algeria: 'DZ',
  'American Samoa': 'AS',
  Andorra: 'AD',
  Argentina: 'AR',
  Armenia: 'AM',
  Australia: 'AU',
  Austria: 'AT',
  Azerbaijan: 'AZ',
  Bahrain: 'BH',
  Bangladesh: 'BD',
  Barbados: 'BB',
  Belarus: 'BY',
  Belgium: 'BE',
  Bermuda: 'BM',
  Brazil: 'BR',
  'British Indian Ocean Territory': 'IO',
  Brunei: 'BN',
  Bulgaria: 'BG',
  Cambodia: 'KH',
  Canada: 'CA',
  'Cape Verde': 'CV',
  Chile: 'CL',
  China: 'CN',
  'Christmas Island': 'CX',
  'Cocos Islands': 'CC',
  Colombia: 'CO',
  'Costa Rica': 'CR',
  Croatia: 'HR',
  Cyprus: 'CY',
  'Czech Republic': 'CZ',
  Denmark: 'DK',
  'Dominican Republic': 'DO',
  Ecuador: 'EC',
  Egypt: 'EG',
  Estonia: 'EE',
  Ethiopia: 'ET',
  'Faroe Islands': 'FO',
  'Falkland Islands': 'FK',
  Finland: 'FI',
  France: 'FR',
  'French Guiana': 'GF',
  'French Polynesia': 'PF',
  Georgia: 'GE',
  Germany: 'DE',
  Gibraltar: 'GI',
  Greece: 'GR',
  Greenland: 'GL',
  Guadeloupe: 'GP',
  Guam: 'GU',
  Guatemala: 'GT',
  Guernsey: 'GG',
  Guinea: 'GN',
  'Guinea-Bissau': 'GW',
  Guyana: 'GY',
  Haiti: 'HT',
  'Heard Island and McDonald Islands': 'HM',
  Honduras: 'HN',
  Hungary: 'HU',
  Iceland: 'IS',
  India: 'IN',
  Indonesia: 'ID',
  Iraq: 'IQ',
  Ireland: 'IE',
  'Isle of Man': 'IM',
  Israel: 'IL',
  Italy: 'IT',
  Jamaica: 'JM',
  Japan: 'JP',
  Jersey: 'JE',
  Jordan: 'JO',
  Kazakhstan: 'KZ',
  Kenya: 'KE',
  Kuwait: 'KW',
  Kyrgyzstan: 'KG',
  Laos: 'LA',
  Latvia: 'LV',
  Lebanon: 'LB',
  Lesotho: 'LS',
  Liberia: 'LR',
  Liechtenstein: 'LI',
  Lithuania: 'LT',
  Luxembourg: 'LU',
  'North Macedonia': 'MK',
  Madagascar: 'MG',
  Malaysia: 'MY',
  Maldives: 'MV',
  Malta: 'MT',
  'Marshall Islands': 'MH',
  Martinique: 'MQ',
  Mauritius: 'MU',
  Mexico: 'MX',
  Micronesia: 'FM',
  Moldova: 'MD',
  Monaco: 'MC',
  Mongolia: 'MN',
  Montenegro: 'ME',
  Morocco: 'MA',
  Mozambique: 'MZ',
  Namibia: 'NA',
  Nauru: 'NR',
  Nepal: 'NP',
  Netherlands: 'NL',
  'New Caledonia': 'NC',
  'New Zealand': 'NZ',
  Nicaragua: 'NI',
  Niger: 'NE',
  Nigeria: 'NG',
  Niue: 'NU',
  'Norfolk Island': 'NF',
  'Northern Mariana Islands': 'MP',
  Norway: 'NO',
  Oman: 'OM',
  Pakistan: 'PK',
  Palau: 'PW',
  Palestine: 'PS',
  Panama: 'PA',
  'Papua New Guinea': 'PG',
  Paraguay: 'PY',
  Peru: 'PE',
  Philippines: 'PH',
  'Pitcairn Islands': 'PN',
  Poland: 'PL',
  Portugal: 'PT',
  'Puerto Rico': 'PR',
  Qatar: 'QA',
  Romania: 'RO',
  Russia: 'RU',
  Rwanda: 'RW',
  'Saint Barthelemy': 'BL',
  'Saint Helena': 'SH',
  'Saint Kitts and Nevis': 'KN',
  'Saint Lucia': 'LC',
  'Saint Martin': 'MF',
  'Saint Pierre and Miquelon': 'PM',
  'Saint Vincent and the Grenadines': 'VC',
  Samoa: 'WS',
  'San Marino': 'SM',
  'Sao Tome and Principe': 'ST',
  'Saudi Arabia': 'SA',
  Senegal: 'SN',
  Serbia: 'RS',
  Seychelles: 'SC',
  'Sierra Leone': 'SL',
  Singapore: 'SG',
  Slovakia: 'SK',
  Slovenia: 'SI',
  'Solomon Islands': 'SB',
  Somalia: 'SO',
  'South Africa': 'ZA',
  'South Georgia and the South Sandwich Islands': 'GS',
  'South Korea': 'KR',
  Spain: 'ES',
  'Sri Lanka': 'LK',
  Sudan: 'SD',
  Suriname: 'SR',
  'Svalbard and Jan Mayen': 'SJ',
  Swaziland: 'SZ',
  Sweden: 'SE',
  Switzerland: 'CH',
  Syria: 'SY',
  Taiwan: 'TW',
  Tajikistan: 'TJ',
  Tanzania: 'TZ',
  Thailand: 'TH',
  'Timor-Leste': 'TL',
  Togo: 'TG',
  Tokelau: 'TK',
  Tonga: 'TO',
  'Trinidad and Tobago': 'TT',
  Tunisia: 'TN',
  Turkey: 'TR',
  Turkmenistan: 'TM',
  'Turks and Caicos Islands': 'TC',
  Tuvalu: 'TV',
  Uganda: 'UG',
  Ukraine: 'UA',
  'United Arab Emirates': 'AE',
  'United Kingdom': 'GB',
  'United States': 'US',
  Uruguay: 'UY',
  Uzbekistan: 'UZ',
  Vanuatu: 'VU',
  'Vatican City': 'VA',
  Venezuela: 'VE',
  Vietnam: 'VN',
  'Virgin Islands': 'VI',
  'Wallis and Futuna': 'WF',
  'Western Sahara': 'EH',
  Yemen: 'YE',
  Zambia: 'ZM',
};

export const countries: string[] = Object.keys(postalCodeRegexes);
