export const routes: Record<string, string> = {
  404: '404',
  '/': 'main',
  '/main': 'main',
  '/goods': 'goods',
  '/login': 'login',
  '/signup': 'signup',
  '/cart': 'cart',
  '/profile': 'profile',
  '/aboutus': 'aboutus',
  '/contact': 'contact',
  '/catalog': 'catalog',
  '/product': 'product',
  '/categories': 'categories',
};
